name: macOS build

on:
  push:
    branches:
      - release
      - m1-mac-build

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
    - run: npm install npm -g
    - run: npm install
    - name: Build MacOS Intel
      run: node_modules/.bin/electron-builder build -m --x64 --publish always
      env:
        GH_TOKEN: ${{ secrets.github_token }}
    - name: Build MacOS M1/ARM
      run: node_modules/.bin/electron-builder build -m --arm64 --publish always
      env:
        GH_TOKEN: ${{ secrets.github_token }}
