name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: Europe/Amsterdam
        timezoneMacos: Europe/Amsterdam
        timezoneWindows: W. Europe Standard Time
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
    - run: npm install npm -g
    - name: Patch node gyp on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - run: npm install
    - run: npx nyc --reporter=lcov npm test
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@v1.1.0
